default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: comminnity_development

test:
  <<: *default
  database: comminnity_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

